apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customerimagebuilds.fnworkflows.acquia.io
spec:
  group: fnworkflows.acquia.io
  names:
    kind: CustomerImageBuild
    listKind: CustomerImageBuildList
    plural: customerimagebuilds
    singular: customerimagebuild
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            gitRef:
              type: string
            imageRepo:
              type: string
            imageTag:
              type: string
            repoURL:
              type: string
            retries:
              format: int32
              type: integer
          required:
          - repoURL
          - gitRef
          - imageRepo
          - imageTag
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
