kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-workflows-operator
subjects:
- kind: ServiceAccount
  name: fn-workflows-operator
  namespace: services
roleRef:
  kind: ClusterRole
  name: fn-workflows-operator
  apiGroup: rbac.authorization.k8s.io
